# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 01:41
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180424_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='termination_grace_period',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
